//HintName: GeneratorTest.TestEFCoreValueConverter.g.cs
// <auto-generated> This file has been auto generated by Intercode Toolbox Typed Primitives. </auto-generated>
#nullable enable

namespace GeneratorTest;

public class TestEFCoreValueConverter: global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<GeneratorTest.Test, global::System.Uri>
{
  public TestEFCoreValueConverter()
    : this( null )
  {
  }

  public TestEFCoreValueConverter(
    global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ConverterMappingHints? mappingHints = null )
    : base(
      primitive => primitive.Value,
      value => ( GeneratorTest.Test ) value,
      mappingHints
    )
  {
  }
}
