// Module Name: EmbeddedResourceManagerTest.cs
// Author:      Eduardo Velasquez
// Copyright (c) 2025, Intercode Consulting, Inc.

namespace Intercode.Toolbox.TypedPrimitives.Tests;

using FluentAssertions;

public class EmbeddedResourceManagerTest
{
  #region Tests

  [Fact]
  public void LoadTemplateResource_ShouldReturnContent_ForKnownPath()
  {
    // Arrange
    var dir = "Common";
    var name = "EFCoreValueConverter";
    var path = EmbeddedResourceManager.GetTemplateResourcePath( dir, name );

    // Act
    var content = EmbeddedResourceManager.LoadTemplateResource( path );

    // Assert
    content.Should().NotBeNullOrWhiteSpace();
    content.Should().Contain( "<auto-generated>" );
  }

  [Fact]
  public void LoadTemplateResource_ShouldThrow_ForUnknownPath()
  {
    // Arrange
    var path = "Intercode.Toolbox.TypedPrimitives.Templates.Common.__Missing__.template";

    // Act
    var act = () => EmbeddedResourceManager.LoadTemplateResource( path );

    // Assert
    act.Should()
       .Throw<InvalidOperationException>()
       .WithMessage( "Could not find embedded resource*" );
  }

  [Fact]
  public void LoadTextResource_ShouldReturnContent_WhenDirectoryAndName()
  {
    // Arrange
    var dir = "Templates.Common";
    var name = "EFCoreValueConverter.template";

    // Act
    var content = EmbeddedResourceManager.LoadTextResource( name, dir );

    // Assert
    content.Should().NotBeNullOrWhiteSpace();
    content.Should().Contain( "EFCoreValueConverter" );
  }

  [Fact]
  public void LoadTextResource_ShouldReturnContent_WhenNameOnly()
  {
    // Arrange
    var name = "Templates.Common.EFCoreValueConverter.template";

    // Act
    var content = EmbeddedResourceManager.LoadTextResource( name );

    // Assert
    content.Should().NotBeNullOrWhiteSpace();
    content.Should().Contain( "EFCoreValueConverter" );
  }

  [Fact]
  public void LoadTextResource_ShouldThrow_ForMissing()
  {
    // Arrange
    var dir = "Templates.Common";
    var name = "__missing__.template";

    // Act
    var act = () => EmbeddedResourceManager.LoadTextResource( name, dir );

    // Assert
    act.Should()
       .Throw<InvalidOperationException>()
       .WithMessage( "Could not find embedded resource*" );
  }

  [Fact]
  public void TemplateExists_ShouldReturnFalse_ForUnknownTemplate()
  {
    // Arrange
    var dir = "Common";
    var name = "__DoesNotExist__";

    // Act
    var exists = EmbeddedResourceManager.TemplateExists( dir, name );

    // Assert
    exists.Should().BeFalse();
  }

  [Fact]
  public void TemplateExists_ShouldReturnTrue_ForKnownTemplate()
  {
    // Arrange
    var dir = "Common";
    var name = "EFCoreValueConverter";
    var path = EmbeddedResourceManager.GetTemplateResourcePath( dir, name );

    // Act
    var exists = EmbeddedResourceManager.TemplateExists( dir, name );

    // Assert
    exists.Should().BeTrue( "template resource should be embedded: {0}", path );
  }

  #endregion
}
