// Module Name: EquatableArrayTest.cs
// Author:      Generated by tests
// Copyright (c) 2025, Intercode Consulting, Inc.

namespace Intercode.Toolbox.TypedPrimitives.Tests;

using FluentAssertions;

public class EquatableArrayTest
{
  #region Tests

  [Fact]
  public void Equals_ShouldBeTrue_ForSameContents()
  {
    // Arrange
    var a1 = new EquatableArray<int>( [1, 2, 3] );
    var a2 = new EquatableArray<int>( [1, 2, 3] );

    // Act / Assert
    a1.Equals( a2 ).Should().BeTrue();
    ( a1 == a2 ).Should().BeTrue();
    ( a1 != a2 ).Should().BeFalse();
  }

  [Fact]
  public void Equals_ShouldBeFalse_ForDifferentLengths()
  {
    // Arrange
    var a1 = new EquatableArray<int>( [1, 2, 3] );
    var a2 = new EquatableArray<int>( [1, 2] );

    // Act / Assert
    a1.Equals( a2 ).Should().BeFalse();
    ( a1 == a2 ).Should().BeFalse();
    ( a1 != a2 ).Should().BeTrue();
  }

  [Fact]
  public void Equals_ShouldBeFalse_ForDifferentContents()
  {
    // Arrange
    var a1 = new EquatableArray<int>( [1, 2, 3] );
    var a2 = new EquatableArray<int>( [1, 2, 4] );

    // Act / Assert
    a1.Equals( a2 ).Should().BeFalse();
  }

  [Fact]
  public void Equals_ShouldUseValueEquality_ForReferenceTypes()
  {
    // Arrange
    var s1 = new[] { new string( 'a', 1 ), new string( 'b', 1 ) };
    var s2 = new[] { "a", "b" };

    var a1 = new EquatableArray<string>( s1 );
    var a2 = new EquatableArray<string>( s2 );

    // Act / Assert
    a1.Equals( a2 ).Should().BeTrue();
  }

  [Fact]
  public void GetHashCode_ShouldMatch_ForEqualArrays()
  {
    // Arrange
    var a1 = new EquatableArray<int>( [10, 20, 30] );
    var a2 = new EquatableArray<int>( [10, 20, 30] );

    // Act / Assert
    a1.GetHashCode().Should().Be( a2.GetHashCode() );
  }

  [Fact]
  public void Length_ShouldReturnExpected_ForNullEmptyAndNonEmpty()
  {
    // Arrange
    var @default = default( EquatableArray<int> );
    var empty = new EquatableArray<int>( [] );
    var some = new EquatableArray<int>( [1, 2, 3, 4] );

    // Act / Assert
    @default.Length.Should().Be( 0 );
    empty.Length.Should().Be( 0 );
    some.Length.Should().Be( 4 );
  }

  [Fact]
  public void GetEnumerator_ShouldEnumerateItems()
  {
    // Arrange
    var items = new[] { 5, 6, 7 };
    var array = new EquatableArray<int>( items );

    // Act
    var enumerated = array.ToArray();

    // Assert
    enumerated.Should().Equal( items );
  }

  [Fact]
  public void GetEnumerator_ShouldBeEmpty_ForDefault()
  {
    // Arrange
    var @default = default( EquatableArray<int> );

    // Act
    var enumerated = @default.ToArray();

    // Assert
    enumerated.Should().BeEmpty();
  }

  [Fact]
  public void AsSpan_ShouldReturnSpan_ForNonNull()
  {
    // Arrange
    var items = new[] { 42, 43 };
    var array = new EquatableArray<int>( items );

    // Act
    var span = array.AsSpan();

    // Assert
    span.Length.Should().Be( items.Length );
    span.ToArray().Should().Equal( items );
  }

  [Fact]
  public void AsSpan_ShouldReturnEmpty_ForDefault()
  {
    // Arrange
    var @default = default( EquatableArray<int> );

    // Act
    var actual = @default.AsSpan();

    // Assert
    actual.IsEmpty.Should().BeTrue();
  }

  [Fact]
  public void Empty_ShouldBehaveAsEmptyArray()
  {
    // Arrange
    var empty = EquatableArray<int>.Empty;
    var alsoEmpty = new EquatableArray<int>( [] );

    // Act / Assert
    empty.Length.Should().Be( 0 );
    empty.ToArray().Should().BeEmpty();
    empty.Equals( alsoEmpty ).Should().BeTrue();
  }

  #endregion
}
