//HintName: GeneratorTest.Test.g.cs
// <auto-generated> This file has been auto generated by Intercode Toolbox Typed Primitives. </auto-generated>
#nullable enable

namespace GeneratorTest;

[global::System.ComponentModel.TypeConverter( typeof( GeneratorTest.Test.TypeConverter ) )]
[global::System.Text.Json.Serialization.JsonConverter( typeof( GeneratorTest.Test.SystemTextJsonConverter ) )]
[global::System.Diagnostics.DebuggerDisplay( "Test = {_value}" )]
public readonly partial record struct Test
  : global::System.IComparable<GeneratorTest.Test>,
    global::System.IComparable,
    global::System.IFormattable
{
  private readonly global::System.Guid? _value;

  private Test( global::System.Guid? value )
  {
    _value = value;
    Normalize( ref _value );
  }

  public global::System.Guid Value
  {
    get
    {
      if( _value is null )
      {
        throw new global::System.InvalidOperationException( "Value is null" );
      }

      return _value.Value;
    }
  }

  public global::System.Guid? ValueOrDefault => _value;
  public bool IsDefault => _value is null;

  public static global::FluentResults.Result<GeneratorTest.Test> Create(
    global::System.Guid? value,
    Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.ValidatorFlags validationMode = default )
  {
    var result = Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.GuidValidator.Validate( value, validationMode );
    if( result.IsFailed )
    {
      return global::FluentResults.Result.Fail<GeneratorTest.Test>( result.Errors );
    }

    return new GeneratorTest.Test( value );
  }

  public static global::FluentResults.Result Validate(
    global::System.Guid? value,
    Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.ValidatorFlags validationMode = default )
  {
    return Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.GuidValidator.Validate( value, validationMode );
  }

  public static bool IsValid(
    global::System.Guid? value,
    Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.ValidatorFlags validationMode = default )
  {
    return Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.GuidValidator.Validate( value, validationMode ).IsSuccess;
  }

  public bool Equals(
    GeneratorTest.Test other )
  {
    return CompareTo( other ) == 0;
  }

  public override int GetHashCode()
  {
    return _value is null ? 0 : _value.GetHashCode();
  }

  public override string ToString()
  {
    return _value is null ? string.Empty : _value.ToString()!;
  }

  public string ToString(
    string? format )
  {
    return _value is null ? string.Empty : _value.Value.ToString( format, null );
  }

  public string ToString(
    string? format,
    global::System.IFormatProvider? formatProvider )
  {
    return _value is null ? string.Empty : _value.Value.ToString( format, formatProvider );
  }

  public int CompareTo(
    object? obj )
  {
    if( obj is GeneratorTest.Test primitive )
    {
      return CompareTo( primitive );
    }

    return 1;
  }

  public int CompareTo(
    GeneratorTest.Test other )
  {
    if( _value is null )
    {
      return other._value is null ? 0 : -1;
    }

    if( other._value is null )
    {
      return 1;
    }

    return ((global::System.Guid) _value).CompareTo( ((global::System.Guid) other) );
  }

  public static explicit operator global::System.Guid(
    GeneratorTest.Test primitive )
  {
    return primitive.Value;
  }

  public static explicit operator GeneratorTest.Test( global::System.Guid? value )
  {
    var result = GeneratorTest.Test.Create( value );
    if( result.IsFailed )
    {
      throw new global::System.InvalidOperationException(
        global::System.Linq.Enumerable.First( result.Errors )
              .Message
      );
    }

    return result.Value;
  }

  public partial class TypeConverter: global::System.ComponentModel.TypeConverter
  {
    public override bool CanConvertFrom(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Type sourceType )
    {
      if ( sourceType == typeof( global::System.Guid ) )
      {
        return true;
      }

      bool canConvert = false;
      CanConvertFromPartial( context, sourceType, ref canConvert );
      return canConvert;
    }

    public override bool CanConvertTo(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Type? destinationType )
    {
      if ( destinationType == typeof( global::System.Guid ) )
      {
        return true;
      }

      bool canConvert = false;
      CanConvertToPartial( context, destinationType, ref canConvert );
      return canConvert;
    }

    public override object? ConvertFrom(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Globalization.CultureInfo? culture,
      object value )
    {
      if ( value is null )
      {
        return ( GeneratorTest.Test ) default;
      }

      if ( value is global::System.Guid rawValue )
      {
        return ( GeneratorTest.Test ) rawValue;
      }

      bool converted = false;
      global::System.Guid? convertedValue = null;
      ConvertFromPartial( context, culture, value, ref convertedValue, ref converted );

      if ( !converted )
      {
        throw new NotSupportedException( string.Format( "Converting from {0} is not supported", value.GetType() ) );
      }

      return ( GeneratorTest.Test ) convertedValue;
    }

    public override object? ConvertTo(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Globalization.CultureInfo? culture,
      object? value,
      global::System.Type destinationType )
    {
      if( value is GeneratorTest.Test primitive )
      {
        if( destinationType == typeof( global::System.Guid ) )
        {
          return primitive.ValueOrDefault;
        }

        bool converted = false;
        object? convertedValue = null;
        ConvertToPartial( context, culture, primitive.ValueOrDefault, destinationType, ref convertedValue, ref converted );

        if ( !converted )
        {
          throw new NotSupportedException( string.Format( "Converting to {0} is not supported", destinationType ) );
        }

        return convertedValue;
      }

      return base.ConvertTo( context, culture, value, destinationType );
    }

    partial void CanConvertFromPartial(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Type sourceType,
      ref bool canConvert );

    partial void CanConvertToPartial(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Type? destinationType,
      ref bool canConvert );

    partial void ConvertFromPartial(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Globalization.CultureInfo? culture,
      object value,
      ref global::System.Guid? convertedValue,
      ref bool converted );

    partial void ConvertToPartial(
      global::System.ComponentModel.ITypeDescriptorContext? context,
      global::System.Globalization.CultureInfo? culture,
      global::System.Guid? value,
      global::System.Type destinationType,
      ref object? convertedValue,
      ref bool converted );
  }

  public partial class SystemTextJsonConverter: global::System.Text.Json.Serialization.JsonConverter<GeneratorTest.Test>
  {
    public override bool CanConvert(
      global::System.Type typeToConvert )
    {
      return typeToConvert == typeof( GeneratorTest.Test );
    }

    public override GeneratorTest.Test Read(
      ref global::System.Text.Json.Utf8JsonReader reader,
      global::System.Type typeToConvert,
      global::System.Text.Json.JsonSerializerOptions options )
    {
      global::System.Guid? value = null;
      if( reader.TokenType != global::System.Text.Json.JsonTokenType.Null )
      {
        if( reader.TokenType == global::System.Text.Json.JsonTokenType.String )
        {
          value = reader.GetGuid();
        }
        else
        {
          bool converted = false;
          ConvertToPartial( ref reader, typeToConvert, options, ref value, ref converted );

          if ( !converted )
          {
            throw new global::System.Text.Json.JsonException( "Value must be a String" );
          }
        }
      }

      var result = GeneratorTest.Test.Create( value );
      if( result.IsFailed )
      {
        throw new global::System.Text.Json.JsonException(
          global::System.Linq.Enumerable.First( result.Errors )
                .Message
        );
      }

      return result.Value;
    }

    public override void Write(
      global::System.Text.Json.Utf8JsonWriter writer,
      GeneratorTest.Test value,
      global::System.Text.Json.JsonSerializerOptions options )
    {
      if ( value.IsDefault )
      {
        writer.WriteNullValue();
        return;
      }

      writer.WriteStringValue( value.ToString() );
    }

    partial void ConvertToPartial(
      ref global::System.Text.Json.Utf8JsonReader reader,
      global::System.Type typeToConvert,
      global::System.Text.Json.JsonSerializerOptions options,
      ref global::System.Guid? value,
      ref bool converted );
  }

  public class ValueConverter: global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<GeneratorTest.Test, global::System.Guid>
  {
    public ValueConverter()
      : this( null )
    {
    }

    public ValueConverter(
      global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ConverterMappingHints? mappingHints = null )
      : base(
        primitive => primitive.Value,
        value => ( GeneratorTest.Test ) value,
        mappingHints
      )
    {
    }
  }


  static partial void Normalize(
    ref global::System.Guid? value );
}
