//HintName: GeneratorTest.Test.g.cs
// <auto-generated> This file has been auto generated by Intercode Toolbox Typed Primitives. </auto-generated>
#nullable enable

namespace GeneratorTest;

[global::System.Diagnostics.DebuggerDisplay( "Test = {_value}" )]
public readonly partial record struct Test
  : global::System.IComparable<GeneratorTest.Test>,
    global::System.IComparable,
    global::System.IFormattable
{
  private readonly long? _value;

  private Test( long? value )
  {
    _value = value;
    Normalize( ref _value );
  }

  public long Value
  {
    get
    {
      if( _value is null )
      {
        throw new global::System.InvalidOperationException( "Value is null" );
      }

      return _value.Value;
    }
  }

  public long? ValueOrDefault => _value;
  public bool IsDefault => _value is null;

  public static global::FluentResults.Result<GeneratorTest.Test> Create( long? value )
  {
    var result = Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.LongValidator.Validate( value );
    if( result.IsFailed )
    {
      return global::FluentResults.Result.Fail<GeneratorTest.Test>( result.Errors );
    }

    return new GeneratorTest.Test( value );
  }

  public static global::FluentResults.Result Validate( long? value )
  {
    return Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.LongValidator.Validate( value );
  }

  public static bool IsValid( long? value )
  {
    return Intercode.Toolbox.TypedPrimitives.SourceGenerationTests.LongValidator.Validate( value ).IsSuccess;
  }

  public bool Equals(
    GeneratorTest.Test other )
  {
    return CompareTo( other ) == 0;
  }

  public override int GetHashCode()
  {
    return _value is null ? 0 : _value.GetHashCode();
  }

  public override string ToString()
  {
    return _value is null ? string.Empty : _value.ToString()!;
  }

  public string ToString(
    string? format )
  {
    return _value is null ? string.Empty : _value.Value.ToString( format, null );
  }

  public string ToString(
    string? format,
    global::System.IFormatProvider? formatProvider )
  {
    return _value is null ? string.Empty : _value.Value.ToString( format, formatProvider );
  }

  public int CompareTo(
    object? obj )
  {
    if( obj is GeneratorTest.Test primitive )
    {
      return CompareTo( primitive );
    }

    return 1;
  }

  public int CompareTo(
    GeneratorTest.Test other )
  {
    if( _value is null )
    {
      return other._value is null ? 0 : -1;
    }

    if( other._value is null )
    {
      return 1;
    }

    return ((long) _value).CompareTo( ((long) other) );
  }

  public static explicit operator long(
    GeneratorTest.Test primitive )
  {
    return primitive.Value;
  }

  public static explicit operator GeneratorTest.Test( long? value )
  {
    var result = GeneratorTest.Test.Create( value );
    if( result.IsFailed )
    {
      throw new global::System.InvalidOperationException(
        global::System.Linq.Enumerable.First( result.Errors )
              .Message
      );
    }

    return result.Value;
  }


  static partial void Normalize(
    ref long? value );
}
