//HintName: GeneratorTest.Test.g.cs
// <auto-generated> This file has been auto generated by Intercode Toolbox Typed Primitives. </auto-generated>
#nullable enable

namespace GeneratorTest;

[global::System.ComponentModel.TypeConverter( typeof( GeneratorTest.TestTypeConverter ) )]
[global::System.Text.Json.Serialization.JsonConverter( typeof( GeneratorTest.TestSystemTextJsonConverter ) )]
[global::System.Diagnostics.DebuggerDisplay( "Test = {_value}" )]
public readonly partial record struct Test
  : global::System.IComparable<GeneratorTest.Test>,
    global::System.IComparable
{
  private readonly string? _value;

  private Test( string? value )
  {
    _value = value;
    Normalize( ref _value );
  }

  public string Value
  {
    get
    {
      if( _value is null )
      {
        throw new global::System.InvalidOperationException( "Value is null" );
      }

      return _value!;
    }
  }

  public string? ValueOrDefault => _value;
  public bool IsDefault => _value is null;

  public static GeneratorTest.Test Create( string? value )
  {
    return new GeneratorTest.Test( global::System.MemoryExtensions.Trim( global::System.MemoryExtensions.AsSpan( value ) ).ToString() );
  }

  public static GeneratorTest.Test Create( global::System.ReadOnlySpan<char> span )
  {
    return new GeneratorTest.Test( global::System.MemoryExtensions.Trim( span ).ToString() );
  }

  public bool Equals(
    GeneratorTest.Test other )
  {
    return CompareTo( other ) == 0;
  }

  public override int GetHashCode()
  {
    return _value is null ? 0 : _value.GetHashCode();
  }

  public override string ToString()
  {
    return _value is null ? string.Empty : _value;
  }

  public string ToString(
    global::System.IFormatProvider? formatProvider )
  {
    return _value is null ? string.Empty : _value.ToString( formatProvider );
  }

  public int CompareTo(
    object? obj )
  {
    if( obj is GeneratorTest.Test primitive )
    {
      return CompareTo( primitive );
    }

    return 1;
  }

  public int CompareTo(
    GeneratorTest.Test other )
  {
    if( _value is null )
    {
      return other._value is null ? 0 : -1;
    }

    if( other._value is null )
    {
      return 1;
    }

    return string.Compare( _value, other._value, System.StringComparison.OrdinalIgnoreCase );
  }

  public static explicit operator string(
    GeneratorTest.Test primitive )
  {
    return primitive.Value;
  }

  public static explicit operator GeneratorTest.Test( string? value )
  {
    return GeneratorTest.Test.Create( value );
  }

  public static explicit operator GeneratorTest.Test( global::System.ReadOnlySpan<char> span )
  {
    return GeneratorTest.Test.Create( span );
  }

  static partial void Normalize(
    ref string? value );
}
