// Module Name: Program.cs
// Author:      Eduardo Velasquez
// Copyright (c) 2025, Intercode Consulting, Inc.

#define USE_SLOTS

// Module Name: Program.cs
// Author:      Eduardo Velasquez
// Copyright (c) 2025, Intercode Consulting, Inc.

using System.Diagnostics;
using Intercode.Toolbox.TemplateEngine;

const string TemplateText = """
  // <auto-generated> This file has been auto generated by Intercode Toolbox Typed Primitives. </auto-generated>
  #nullable enable

  namespace $Namespace$;

  public partial class $TypeName$SystemTextJsonConverter: global::System.Text.Json.Serialization.JsonConverter<$TypeQualifiedName$>
  {
    public override bool CanConvert(
      global::System.Type typeToConvert )
    {
      return typeToConvert == typeof( $TypeQualifiedName$ );
    }

    public override $TypeQualifiedName$ Read(
      ref global::System.Text.Json.Utf8JsonReader reader,
      global::System.Type typeToConvert,
      global::System.Text.Json.JsonSerializerOptions options )
    {
      $TypeKeyword$? value = null;
      if( reader.TokenType != global::System.Text.Json.JsonTokenType.Null )
      {
        if( reader.TokenType == global::System.Text.Json.JsonTokenType.$JsonTokenType$ )
        {
          value = $JsonReader$;
        }
        else
        {
          bool converted = false;
          ConvertToPartial( ref reader, typeToConvert, options, ref value, ref converted );

          if ( !converted )
          {
            throw new global::System.Text.Json.JsonException( "Value must be a $JsonTokenType$" );
          }
        }
      }

      var result = $TypeQualifiedName$.Create( value );
      if( result.IsFailed )
      {
        throw new global::System.Text.Json.JsonException(
          global::System.Linq.Enumerable.First( result.Errors )
                .Message
        );
      }

      return result.Value;
    }

    public override void Write(
      global::System.Text.Json.Utf8JsonWriter writer,
      $TypeQualifiedName$ value,
      global::System.Text.Json.JsonSerializerOptions options )
    {
      if ( value.IsDefault )
      {
        writer.WriteNullValue();
        return;
      }

      $JsonWriter$;
    }

    partial void ConvertToPartial(
      ref global::System.Text.Json.Utf8JsonReader reader,
      global::System.Type typeToConvert,
      global::System.Text.Json.JsonSerializerOptions options,
      ref $TypeKeyword$? value,
      ref bool converted );
  }
  """;

var macroTable = new MacroTableBuilder()
                 .Declare( "Namespace" )
                 .Declare( "TypeName" )
                 .Declare( "TypeQualifiedName" )
                 .Declare( "TypeKeyword" )
                 .Declare( "JsonTokenType" )
                 .Declare( "JsonReader" )
                 .Declare( "JsonWriter" )
                 .Build();

var template = TemplateCompiler.Compile( macroTable, TemplateText );

var macroValues = macroTable.CreateValues()
                            .SetValue( "Namespace", "MyApp.Primitives" )
                            .SetValue( "TypeKeyword", "string" )
                            .SetValue( "JsonTokenType", "String" )
                            .SetValue( "JsonReader", "reader.GetString()" )
                            .SetValue( "JsonWriter", "writer.WriteStringValue( value.Value );" );

var timer = Stopwatch.StartNew();
var iterations = 1_000_000;

#if USE_SLOTS
var typeNameSlot = macroTable.GetSlot( "TypeName" );
var typeQualifiedNameSlot = macroTable.GetSlot( "TypeQualifiedName" );
#endif

for( var i = 0; i < iterations; i++ )
{
#if USE_SLOTS
  macroValues.SetValue( typeNameSlot, $"Type{i}" )
             .SetValue( typeQualifiedNameSlot, $"MyApp.Primitives.Type{i}" );
#else
    macroValues.SetValue( "TypeName", $"Type{i}" )
               .SetValue( "TypeQualifiedName", $"MyApp.Primitives.Type{i}" );
#endif

  var processed = MacroProcessor.ProcessMacros( template, macroValues );
}

timer.Stop();

Console.WriteLine(
  $"Processed {iterations:N0} templates in {CalcElapsed( timer.Elapsed.TotalNanoseconds )} ({CalcElapsed( timer.Elapsed.TotalNanoseconds / iterations )} per template)"
);
return;

static string CalcElapsed(
  double totalNanoseconds )
{
  if( totalNanoseconds >= 1_000_000_000L )
  {
    return $"{totalNanoseconds / 1_000_000_000.0:N2} s";
  }

  if( totalNanoseconds >= 1_000_000L )
  {
    return $"{totalNanoseconds / 1_000_000.0:N2} ms";
  }

  if( totalNanoseconds >= 1_000L )
  {
    return $"{totalNanoseconds / 1_000.0:N2} µs";
  }

  return $"{totalNanoseconds:N2} ns";
}
